ALTER TABLE IF EXISTS ONLY "sources" DROP COLUMN IF EXISTS "metadata";
ALTER TABLE IF EXISTS ONLY "workspaces" DROP COLUMN IF EXISTS "metadata";
ALTER TABLE IF EXISTS ONLY "plugins" DROP COLUMN IF EXISTS "metadata";

