ALTER TABLE IF EXISTS ONLY "sources" ADD COLUMN IF NOT EXISTS "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS ONLY "workspaces" ADD COLUMN IF NOT EXISTS "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS ONLY "plugins" ADD COLUMN IF NOT EXISTS "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb;
