ALTER TABLE IF EXISTS ONLY "workspaces" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "workspaces" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE IF EXISTS ONLY "sources" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "sources" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE IF EXISTS ONLY "plugins" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "plugins" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE IF EXISTS ONLY "events" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "events" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE IF EXISTS ONLY "endpoints" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "endpoints" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE IF EXISTS ONLY "attempts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "attempts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE IF EXISTS ONLY "attempt_details" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE IF EXISTS ONLY "attempt_details" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP(3);
