version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/webhookx-io/webhookx/config.COMMIT={{ .ShortCommit }}
      - -X github.com/webhookx-io/webhookx/config.VERSION={{ .Tag }}

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: webhookx-io
      name: homebrew-webhookx
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    commit_author:
      name: "WebhookX"
      email: "webhookx@gmail.com"
    homepage: "https://github.com/webhookx-io/webhookx"
    description: "an open-source webhooks gateway for message receiving, processing, and delivering."
    test: |
      system "#{bin}/webhookx", "version"
