[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "index"
path = "index.rs"

[dependencies]
wee_alloc = "0.4.5"
serde_json = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
